version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL}
      - OPENAI_BASE_MODEL=${OPENAI_BASE_MODEL}
    volumes:
      - ${PB_DATA_VOLUME:-./server/pb_data}:/root/pb_data
      - ./server/migrations:/root/pb_migrations
    networks:
      - textly-network
    restart: ${RESTART_POLICY:-no}

  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_POCKETBASE_URL=${POCKETBASE_URL:-http://localhost:8080}
    depends_on:
      - backend
    networks:
      - textly-network
    restart: ${RESTART_POLICY:-no}

networks:
  textly-network:
    driver: bridge

volumes:
  pb_data:
    name: ${PB_DATA_VOLUME_NAME:-textly_pb_data} 